/*
 * check.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import json.JSONArray;
import json.JSONObject;

import date.demon_1;

/**
 *
 * @author  __USER__
 */
public class check extends javax.swing.JFrame {

	String comment;
	String result;

	/** Creates new form check */
	public check() {
		initComponents();
		this.setLocationRelativeTo(null);
		jScrollPane1
		.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel2 = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel1.setText("\u6770\u54e5\u5feb\u9012");

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel2.setText("\u8bf7\u8f93\u5165\u8fd0\u5355\u53f7\uff1a");

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 660,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 281,
				Short.MAX_VALUE));

		jScrollPane1.setViewportView(jPanel2);

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING)
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				109,
																				109,
																				109)
																		.add(
																				jScrollPane1,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				662,
																				Short.MAX_VALUE))
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				383,
																				383,
																				383)
																		.add(
																				jLabel1))
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				67,
																				67,
																				67)
																		.add(
																				jLabel2)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jTextField1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				494,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(
																				jButton1)))
										.addContainerGap(141, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel1Layout.createSequentialGroup().addContainerGap().add(
						jLabel1).add(55, 55, 55).add(
						jPanel1Layout.createParallelGroup(
								org.jdesktop.layout.GroupLayout.BASELINE).add(
								jLabel2).add(jTextField1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jButton1)).add(81, 81, 81).add(
						jScrollPane1,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 283,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(33, Short.MAX_VALUE)));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		showresult();
	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
		} catch (Exception e) {
			//TODO exception
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new check().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables
	
	ArrayList<JTextArea> ta = new ArrayList<JTextArea>();
	ArrayList<JPanel> jPanels = new ArrayList<JPanel>();
	Font font=new Font("微软雅黑",Font.PLAIN,18);
	private void showresult(){
		String comment = jTextField1.getText();
		this.comment = comment;
		demon_1 demon = new demon_1();
		if (comment == null) {
			JOptionPane.showMessageDialog(this, "请输入你的运单号！");
		} else {

			JSONObject jo = new JSONObject(demon.result("Auto", this.comment));
			JSONObject jo1 = new JSONObject(jo.get("showapi_res_body")
					.toString());
			JSONArray ja = new JSONArray(jo1.get("data").toString());
			JSONObject o;
			
			for (int i = 0; i < ja.length(); i++) {
				o = new JSONObject(ja.get(i).toString());
				

				/*首先放一个面板进去*/
				jPanels.add(new JPanel());
				jPanels.get(i).setSize(jPanel2.getWidth(), 80);
				jPanels.get(i).setBounds(0, jPanels.get(i).getHeight() * i,
						jPanel2.getWidth(), 80);
				jPanels.get(i).setBorder(
						BorderFactory.createMatteBorder(0, 0, 1, 0,
								Color.LIGHT_GRAY));
				jPanels.get(i).setBackground(Color.WHITE);
				
				/*设置jPanel面板最大值*/
				Dimension ds = new Dimension(jPanel2.getWidth(), jPanels.get(i)
						.getHeight()
						* i + 80);
				jPanel2.setPreferredSize(ds);
				jPanel2.add(jPanels.get(i));

				
				
				
				
				ta.add(new JTextArea());
				ta.get(i).setText(o.get("time").toString()+"       "+o.get("context").toString());
				ta.get(i).setSize(600,70);
				ta.get(i).setFont(font);
				
				ta.get(i).setLineWrap(true);//自动换行
				ta.get(i).setEditable(false);//模仿JLabel 禁止编辑文字
				jPanels.get(i).add(ta.get(i));
			}
			
		}
	}

}